
project_id = "bbonngdyfyfjqfhvoljl"

[functions.flight-search]
path = "supabase/functions/flight-search"

[functions.create-booking]
path = "supabase/functions/create-booking"

[functions.stripe-webhook]
path = "supabase/functions/stripe-webhook"
verify_jwt = false

[functions.create-setup-session]
path = "supabase/functions/create-setup-session"

[functions.create-payment-session]
path = "supabase/functions/create-payment-session"
