services:
  # Production environment (default)
  parker-flight:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_FLAG_FS_V2=${VITE_FLAG_FS_V2:-true}
    container_name: parker-flight-app
    restart: unless-stopped
    # Resource limits and security constraints for MVP
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 128M
          cpus: "0.1"
    # Security enhancements
    security_opt:
      - no-new-privileges:true
    ports:
      - "${EXTERNAL_PORT:-80}:80"  # Flexible external port mapping
    environment:
      - NODE_ENV=production
      - PORT=80  # Internal nginx port
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
      - VITE_FLAG_FS_V2=${VITE_FLAG_FS_V2:-true}
    volumes:
      # Optional: Custom nginx config override
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - parker-flight-network
    labels:
      - "com.docker.compose.service=parker-flight"
      - "version=1.5.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy with SSL termination
  # Uncomment if you want HTTPS support
  # nginx-proxy:
  #   image: nginx:alpine
  #   container_name: parker-flight-proxy
  #   restart: unless-stopped
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./docker/ssl-nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - /path/to/ssl/certs:/etc/nginx/certs:ro
  #   depends_on:
  #     - parker-flight
  #   networks:
  #     - parker-flight-network

networks:
  parker-flight-network:
    driver: bridge

# Optional: Add volumes for logs or persistent data
volumes:
  app_logs:
