-- Insert test user if doesn't exist
INSERT INTO auth.users (
    id,
    email,
    created_at,
    updated_at,
    email_confirmed_at,
    phone_confirmed_at,
    confirmation_sent_at,
    recovery_sent_at,
    email_change_sent_at,
    new_email,
    invited_at,
    action_link,
    email_change,
    email_change_confirm_status,
    banned_until,
    reauthentication_sent_at,
    reauthentication_token,
    email_change_token_new,
    email_change_token_current,
    phone_change,
    phone_change_token,
    phone_change_sent_at,
    confirmed_at,
    email_change_token,
    phone,
    phone_change_confirm_status,
    instance_id,
    aud,
    role
) VALUES (
    '123e4567-e89b-12d3-a456-426614174000',
    'test@example.com',
    NOW(),
    NOW(),
    NOW(),
    NULL,
    NULL,
    NULL,
    NULL,
    '',
    NULL,
    '',
    '',
    0,
    NULL,
    NULL,
    '',
    '',
    '',
    '',
    '',
    NULL,
    NOW(),
    '',
    '',
    0,
    '00000000-0000-0000-0000-000000000000',
    'authenticated',
    'authenticated'
) ON CONFLICT (id) DO NOTHING;

-- Insert test trip request with current dates
INSERT INTO trip_requests (
    id,
    user_id,
    earliest_departure,
    latest_departure,
    departure_date,
    return_date,
    min_duration,
    max_duration,
    budget,
    max_price,
    origin_location_code,
    departure_airports,
    destination_airport,
    destination_location_code,
    nonstop_required,
    baggage_included_required,
    auto_book_enabled,
    created_at,
    updated_at
) VALUES (
    '02a4b42e-5691-4c37-ac7e-f220e2e74ed8',
    '123e4567-e89b-12d3-a456-426614174000',
    '2025-07-15 00:00:00+00',
    '2025-07-16 23:59:59+00',
    '2025-07-15',
    '2025-07-18',
    3,
    7,
    1000,
    1000,
    'NYC',
    ARRAY['JFK', 'LGA'],
    'LAX',
    'LAX',
    false,
    false,
    false,
    NOW(),
    NOW()
) ON CONFLICT (id) DO UPDATE SET
    departure_date = EXCLUDED.departure_date,
    return_date = EXCLUDED.return_date,
    updated_at = NOW();

-- Also insert the backup test trip
INSERT INTO trip_requests (
    id,
    user_id,
    earliest_departure,
    latest_departure,
    departure_date,
    return_date,
    min_duration,
    max_duration,
    budget,
    max_price,
    origin_location_code,
    departure_airports,
    destination_airport,
    destination_location_code,
    nonstop_required,
    baggage_included_required,
    auto_book_enabled,
    created_at,
    updated_at
) VALUES (
    'ba85c75a-3087-4141-bccf-d636f77fffbc',
    '123e4567-e89b-12d3-a456-426614174000',
    '2025-07-15 00:00:00+00',
    '2025-07-16 23:59:59+00',
    '2025-07-15',
    '2025-07-18',
    3,
    7,
    1000,
    1000,
    'NYC',
    ARRAY['JFK'],
    'LHR',
    'LHR',
    true,
    true,
    false,
    NOW(),
    NOW()
) ON CONFLICT (id) DO UPDATE SET
    departure_date = EXCLUDED.departure_date,
    return_date = EXCLUDED.return_date,
    updated_at = NOW();
