global:
  resolve_timeout: 5m
  smtp_from: '${SMTP_FROM}'
  smtp_smarthost: '${SMTP_HOST}:${SMTP_PORT}'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'email-notifications'
      repeat_interval: 1h
      continue: true
    - match:
        severity: warning
      receiver: 'email-notifications'
      repeat_interval: 2h
      continue: true

receivers:
- name: 'email-notifications'
  email_configs:
  - to: '${ALERT_EMAIL_TO}'
    send_resolved: true
    html: |
      <h3>Alert: {{ .CommonLabels.alertname }}</h3>
      <p><strong>Status:</strong> {{ .Status }}</p>
      {{ range .Alerts }}
      <hr>
      <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
      <p><strong>Description:</strong> {{ .Annotations.description }}</p>
      <p><strong>Details:</strong></p>
      <ul>
      {{ range .Labels.SortedPairs }}
        <li><strong>{{ .Name }}:</strong> {{ .Value }}</li>
      {{ end }}
      </ul>
      {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
