groups:
- name: system_alerts
  rules:
  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High CPU usage on {{ $labels.instance }}
      description: CPU usage is above 85% for 5 minutes

  - alert: HighMemoryUsage
    expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High memory usage on {{ $labels.instance }}
      description: Memory usage is above 85% for 5 minutes

  - alert: DiskSpaceRunningOut
    expr: (node_filesystem_size_bytes{mountpoint="/"} - node_filesystem_free_bytes{mountpoint="/"}) / node_filesystem_size_bytes{mountpoint="/"} * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: Disk space running out on {{ $labels.instance }}
      description: Disk usage is above 85% for 5 minutes

  - alert: ContainerCPUUsage
    expr: rate(container_cpu_usage_seconds_total{name!=""}[5m]) * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High CPU usage in container {{ $labels.name }}
      description: Container CPU usage is above 85% for 5 minutes

  - alert: ContainerMemoryUsage
    expr: container_memory_usage_bytes{name!=""} / container_spec_memory_limit_bytes{name!=""} * 100 > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: High memory usage in container {{ $labels.name }}
      description: Container memory usage is above 85% for 5 minutes

  - alert: ServiceDown
    expr: up == 0
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: Service {{ $labels.job }} is down
      description: Service has been down for more than 1 minute
