# Development overrides for docker-compose.yml
# This file is automatically loaded by Docker Compose
# Use this for development-specific configurations

version: '3.8'

services:
  parker-flight:
    build:
      target: build  # Use build stage for development
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - VITE_DEBUG=true
    ports:
      - "3000:80"  # Different port for development
    volumes:
      # Mount source code for live development
      - ./src:/app/src:ro
      - ./public:/app/public:ro
      # Override nginx config for development
      - ./docker/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    # Remove security restrictions for development
    read_only: false
    tmpfs: []
    cap_drop: []
    cap_add: []
    security_opt: []
    # Faster health check for development
    healthcheck:
      interval: 10s
      timeout: 5s
      start_period: 10s
