apiVersion: 1
datasources:
  - name: prometheus-dev
    type: prometheus
    access: proxy
    url: http://prometheus-development:9090
    isDefault: false
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: High
      incrementalQuerying: false
      incrementalQueryOverlapWindow: 10m
      queryTimeout: 60s
      defaultRegion: us-east-1
      customQueryParameters: environment=development
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger
          url: http://jaeger:16686/trace/${__value.raw}
    secureJsonData:
    version: 1
  - name: prometheus-staging
    type: prometheus
    access: proxy
    url: http://prometheus-staging:9090
    isDefault: false
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: High
      incrementalQuerying: false
      incrementalQueryOverlapWindow: 10m
      queryTimeout: 60s
      defaultRegion: us-east-1
      customQueryParameters: environment=staging
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger
          url: http://jaeger:16686/trace/${__value.raw}
    secureJsonData:
    version: 1
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: High
      incrementalQuerying: false
      incrementalQueryOverlapWindow: 10m
      queryTimeout: 60s
      defaultRegion: us-east-1
      customQueryParameters: environment=production
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger
          url: http://jaeger:16686/trace/${__value.raw}
    secureJsonData:
    version: 1
