AWSTemplateFormatVersion: '2010-09-09'
Description: 'GitHub Link Buddy - Core AWS Optimization Infrastructure'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues: [development, staging, production]
    Description: Environment name for resource naming
  
  ApplicationName:
    Type: String
    Default: github-link-buddy
    Description: Application name for consistent resource naming
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID for resource deployment
  
  PrivateSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Private subnet IDs for secure resource placement
  
  PublicSubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Public subnet IDs for ALB deployment
  
  CertificateArn:
    Type: String
    Description: SSL certificate ARN for HTTPS termination
  
  DomainName:
    Type: String
    Description: Primary domain name for the application
  
  NotificationEmail:
    Type: String
    Description: Email for notifications and alerts

Conditions:
  IsProduction: !Equals [!Ref Environment, 'production']

Resources:
  # Multi-region KMS Key for encryption
  PrimaryKMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: 'Primary encryption key for GitHub Link Buddy'
      KeyPolicy:
        Version: '2012-10-17'
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: 'kms:*'
            Resource: '*'
          - Sid: Allow AWS Services
            Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
                - dynamodb.amazonaws.com
                - lambda.amazonaws.com
                - backup.amazonaws.com
                - secretsmanager.amazonaws.com
                - xray.amazonaws.com
            Action:
              - kms:Decrypt
              - kms:GenerateDataKey
              - kms:CreateGrant
            Resource: '*'
      EnableKeyRotation: true
      MultiRegion: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref ApplicationName

  PrimaryKMSKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub 'alias/${ApplicationName}-primary-${Environment}'
      TargetKeyId: !Ref PrimaryKMSKey

  # DynamoDB Table (Single Region)
  LinksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ApplicationName}-links-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdAt
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true
        KMSMasterKeyId: !Ref PrimaryKMSKey
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref ApplicationName
        - Key: BackupEnabled
          Value: 'true'

  # S3 Bucket with Intelligent Tiering
  PrimaryS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ApplicationName}-primary-${AWS::AccountId}-${Environment}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Ref PrimaryKMSKey
            BucketKeyEnabled: true
      IntelligentTieringConfigurations:
        - Id: EntireBucketIntelligentTiering
          Status: Enabled
          Tierings:
            - AccessTier: ARCHIVE_ACCESS
              Days: 90
            - AccessTier: DEEP_ARCHIVE_ACCESS
              Days: 180
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: OptimizeStorage
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
              - TransitionInDays: 365
                StorageClass: DEEP_ARCHIVE
            NoncurrentVersionTransitions:
              - TransitionInDays: 30
                StorageClass: STANDARD_IA
              - TransitionInDays: 90
                StorageClass: GLACIER
            NoncurrentVersionExpirationInDays: 730
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref ApplicationName

  # X-Ray Sampling Rules for distributed tracing
  CriticalEndpointsSamplingRule:
    Type: AWS::XRay::SamplingRule
    Properties:
      SamplingRule:
        RuleName: !Sub 'critical-${Environment}'
        Priority: 1000
        FixedRate: 1.0
        ReservoirSize: 10
        ServiceName: !Sub '${ApplicationName}-api-${Environment}'
        ServiceType: 'AWS::Lambda::Function'
        Host: '*'
        HTTPMethod: '*'
        URLPath: '/api/v1/links*'
        Version: 1
        ResourceARN: '*'
        Attributes: {}

  ErrorSamplingRule:
    Type: AWS::XRay::SamplingRule
    Properties:
      SamplingRule:
        RuleName: !Sub 'errors-${Environment}'
        Priority: 2000
        FixedRate: 1.0
        ReservoirSize: 5
        ServiceName: '*'
        ServiceType: '*'
        Host: '*'
        HTTPMethod: '*'
        URLPath: '*'
        Version: 1
        ResourceARN: '*'
        Attributes:
          error: 'true'

  # CloudWatch Dashboard for comprehensive monitoring
  ComprehensiveMonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${ApplicationName}-monitoring-${Environment}'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/DynamoDB", "ConsumedReadCapacityUnits", "TableName", "${LinksTable}", { "stat": "Sum" } ],
                  [ ".", "ConsumedWriteCapacityUnits", ".", ".", { "stat": "Sum" } ],
                  [ ".", "ThrottledRequests", ".", ".", { "stat": "Sum" } ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "DynamoDB Performance",
                "period": 300
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/S3", "BucketSizeBytes", "BucketName", "${PrimaryS3Bucket}", "StorageType", "StandardStorage" ],
                  [ ".", "NumberOfObjects", ".", ".", ".", "AllStorageTypes" ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "${AWS::Region}",
                "title": "S3 Storage Metrics",
                "period": 86400
              }
            }
          ]
        }

  # CloudWatch Alarms for critical metrics
  DynamoDBThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ApplicationName}-dynamodb-throttle-${Environment}'
      AlarmDescription: 'DynamoDB throttling detected'
      MetricName: ThrottledRequests
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: TableName
          Value: !Ref LinksTable
      AlarmActions:
        - !Ref AlertNotificationTopic

  # SNS Topic for Alerts
  AlertNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ApplicationName}-alerts-${Environment}'
      KmsMasterKeyId: !Ref PrimaryKMSKey

  AlertNotificationSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn: !Ref AlertNotificationTopic
      Endpoint: !Ref NotificationEmail

  # AWS Secrets Manager for secure credential management
  DatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ApplicationName}/database/${Environment}'
      Description: 'Database credentials for GitHub Link Buddy'
      GenerateSecretString:
        SecretStringTemplate: !Sub |
          {
            "username": "${ApplicationName}_user",
            "engine": "postgres",
            "host": "localhost",
            "port": 5432,
            "dbname": "${ApplicationName}_${Environment}"
          }
        GenerateStringKey: 'password'
        PasswordLength: 32
        ExcludeCharacters: '"@/\'
        RequireEachIncludedType: true
      KmsKeyId: !Ref PrimaryKMSKey
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref ApplicationName

  APIKeysSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ApplicationName}/api-keys/${Environment}'
      Description: 'External API keys and tokens'
      SecretString: !Sub |
        {
          "github_token": "ghp_placeholder_token_${Environment}",
          "jwt_secret": "jwt_secret_placeholder_${Environment}",
          "oauth_client_id": "oauth_client_id_placeholder",
          "oauth_client_secret": "oauth_client_secret_placeholder",
          "supabase_url": "https://your-project.supabase.co",
          "supabase_anon_key": "your_supabase_anon_key"
        }
      KmsKeyId: !Ref PrimaryKMSKey
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: !Ref ApplicationName

Outputs:
  DynamoDBTableName:
    Description: 'DynamoDB table name for the application'
    Value: !Ref LinksTable
    Export:
      Name: !Sub '${ApplicationName}-dynamodb-table-${Environment}'

  S3BucketName:
    Description: 'S3 bucket name for file storage'
    Value: !Ref PrimaryS3Bucket
    Export:
      Name: !Sub '${ApplicationName}-s3-bucket-${Environment}'

  KMSKeyId:
    Description: 'KMS Key ID for encryption'
    Value: !Ref PrimaryKMSKey
    Export:
      Name: !Sub '${ApplicationName}-kms-key-${Environment}'

  DatabaseSecretArn:
    Description: 'ARN of the database credentials secret'
    Value: !Ref DatabaseSecret
    Export:
      Name: !Sub '${ApplicationName}-database-secret-${Environment}'

  APIKeysSecretArn:
    Description: 'ARN of the API keys secret'
    Value: !Ref APIKeysSecret
    Export:
      Name: !Sub '${ApplicationName}-api-keys-secret-${Environment}'
