ALTER TABLE bookings
ADD COLUMN email_reminder_sent BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN sms_reminder_sent BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN one_hour_email_sent BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN one_hour_sms_sent BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN second_reminder_scheduled_at TIMESTAMP NULL;
