name: CI Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Assuming npm is used, change to 'yarn' if needed

      - name: Install dependencies
        run: npm ci # Use 'yarn install --frozen-lockfile' if using Yarn

      - name: Build project
        run: npm run build # Assuming 'npm run build' is the build command

      - name: Run tests with coverage
        # This assumes Vitest is configured to output coverage reports (e.g., in lcov format)
        # and that the test script will fail if coverage is below the threshold (e.g., 80%)
        # defined in vitest.config.ts or via CLI options within the script.
        run: npm run test -- --coverage

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always() # Upload coverage even if previous steps fail, for inspection
        with:
          name: coverage-report-node-${{ matrix.node-version }}
          path: coverage/ # Default Vitest coverage directory, adjust if different
          retention-days: 7
