name: E2E Smoke on PRs

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  e2e-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack (pnpm from package.json)
        run: corepack enable

      - name: Prepare pnpm via Corepack
        run: |
          PNPM_VERSION=$(node -p "require('./package.json').packageManager.split('@')[1]")
          corepack prepare pnpm@${PNPM_VERSION} --activate

      - name: Configure pnpm store
        run: |
          pnpm config set store-dir ~/.pnpm-store
          pnpm config set side-effects-cache false
      - name: Install dependencies
        run: |
          for i in 1 2 3; do
            pnpm install --frozen-lockfile && break || {
              echo "pnpm install failed (attempt $i). Retrying in $((i*5))s...";
              pnpm store prune || true
              sleep $((i*5));
            }
          done

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build app
        run: pnpm build

      - name: Run E2E critical tests
        run: |
          pnpm preview -- --host 0.0.0.0 --strictPort --port 8080 > preview.log 2>&1 &
          npx -y wait-on tcp:127.0.0.1:8080
          curl -sf http://127.0.0.1:8080/ || { echo 'Preview failed to respond'; cat preview.log || true; exit 1; }
          pnpm run test:e2e:critical
        env:
          CI: '1'
          E2E_BASE_URL: http://127.0.0.1:8080
          PORT: 8080

