name: Edge Functions - Fast Path

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'supabase/functions/**'
      - '.github/workflows/edge-fast.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  lint-and-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.5
          run_install: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Lint
        run: pnpm run lint

      - name: Functions tests
        run: pnpm run test:functions
        env:
          VITEST: '1'

