name: Edge Functions - Fast Path

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'supabase/functions/**'
      - '.github/workflows/edge-fast.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  lint-and-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack (pnpm from package.json)
        run: corepack enable

      - name: Prepare pnpm via Corepack
        run: |
          PNPM_VERSION=$(node -p "require('./package.json').packageManager.split('@')[1]")
          corepack prepare pnpm@${PNPM_VERSION} --activate

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Functions tests
        run: pnpm run test:functions
        env:
          VITEST: '1'

