name: Functions Tests

on:
  pull_request:
    paths:
      - 'supabase/functions/**'
      - '.github/workflows/functions-tests.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'
  workflow_dispatch: {}

jobs:
  test-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Run functions tests
        run: |
          pnpm run test:functions
        env:
          VITEST: '1'
