name: Functions Tests

on:
  pull_request:
    paths:
      - 'supabase/functions/**'
      - '.github/workflows/functions-tests.yml'
      - 'package.json'
      - 'pnpm-lock.yaml'
  workflow_dispatch: {}

jobs:
  test-functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Enable Corepack (pnpm from package.json)
        run: corepack enable

      - name: Prepare pnpm via Corepack
        run: |
          PNPM_VERSION=$(node -p "require('./package.json').packageManager.split('@')[1]")
          corepack prepare pnpm@${PNPM_VERSION} --activate

      - name: Install dependencies
        run: |
          for i in 1 2 3; do
            pnpm install --frozen-lockfile && break || {
              echo "pnpm install failed (attempt $i). Retrying in $((i*5))s...";
              sleep $((i*5));
            }
          done

      - name: Run functions tests
        run: pnpm exec vitest run supabase/functions/tests --reporter=dot --passWithNoTests
        env:
          VITEST: '1'
