name: Migrations Dry-Run

on:
  pull_request:
  push:
    branches: [ main, staging ]

jobs:
  migrations-dry-run:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: supabase_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Supabase CLI
        run: |
          curl -sL https://app.supabase.com/cli/install | sh
          echo "$HOME/.supabase/bin" >> $GITHUB_PATH

      - name: Wait for Postgres
        run: |
          for i in {1..30}; do
            pg_isready -h localhost -p 5432 -U postgres && break
            sleep 1
          done

      - name: Run migrations on fresh DB
        env:
          TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/supabase_test
        run: |
          supabase --version
          supabase db reset --db-url "$TEST_DATABASE_URL" --force

      - name: Verify schema objects
        env:
          TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/supabase_test
        run: |
          psql "$TEST_DATABASE_URL" -c "\dt+ public.*" || true

