name: Security and Secrets Scan

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable Corepack (pnpm from package.json)
        run: corepack enable

      - name: Prepare pnpm via Corepack
        run: |
          PNPM_VERSION=$(node -p "require('./package.json').packageManager.split('@')[1]")
          corepack prepare pnpm@${PNPM_VERSION} --activate

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Install git-secrets
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          git clone https://github.com/awslabs/git-secrets.git
          sudo make -C git-secrets install

      - name: Run npm audit (fail on high/critical)
        run: |
          # Using npm audit via pnpm environment to surface high/critical issues
          set -e
          npx npm@10 audit --production --audit-level=high


      - name: Scan repository for secrets
        run: |
          git secrets --install
          git secrets --register-aws
          git secrets --scan -r .

