name: CI - Test Matrix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Run ${{ matrix.suite }} tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite: [unit, integration, edge]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8.15.5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set env for analytics flag (disabled by default)
        run: |
          echo "VITE_FEATURE_ANALYTICS_SUBMIT=false" >> $GITHUB_ENV

      - name: Run unit tests
        if: matrix.suite == 'unit'
        run: pnpm run test:unit

      - name: Run integration tests
        if: matrix.suite == 'integration'
        run: pnpm run test:integration

      - name: Run edge tests
        if: matrix.suite == 'edge'
        run: pnpm run test:edge
